version: '3'

volumes:
  cache:
    driver: local
  db-data:
    driver: local

networks:
  app:
    driver: bridge

services:

  redis:
    networks:
      - app
    image: redis:7.2-rc-alpine
    container_name: redis-vk
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  project:
    build: /
    container_name: project-vk
    networks:
      - app
    depends_on:
      - redis
      - postgres
    ports:
      - '8080:8080'
    env_file:
      - .env

  postgres:
    image: postgres:15.1-alpine
    container_name: db-vk
    networks:
      - app
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
