server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  config:
    activate:
      on-profile: docker

logging:
  level:
    org:
      springframework:
        security: DEBUG

json:
  placeholder:
    url: https://jsonplaceholder.typicode.com/