server:
  port: 8080


spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/vk-project
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: password

logging:
  level:
    org:
      springframework:
        security: DEBUG

json:
  placeholder:
    url: https://jsonplaceholder.typicode.com/

