create table if not exists users
(
    id       bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    password varchar(255) not null
);

create table if not exists user_roles
(
    app_user_id bigint      not null references users (id) on delete cascade,
    role    varchar(64) not null,
    primary key (app_user_id, role)
);