create table if not exists users
(
    id bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    password varchar(255) not null
);

create table if not exists user_roles
(
    app_user_id bigint not null references users (id) on delete cascade,
    role varchar(64) not null,
    primary key (app_user_id, role)
);

create table if not exists requests
(
    id bigint generated by default as identity primary key,
    sent_at timestamp not null,
    path varchar(255) not null,
    method varchar(32) not null,
    is_allowed boolean not null,
    app_user_id bigint not null references users (id) on delete cascade
)